const mongoose = require('mongoose');

const pingryInternalSchema = new mongoose.Schema ({
  shortHills7DayIsolationQuarantine: Number,
  baskingRidge7DayIsolationQuarantine: Number,
  averages: [],
  data: [{studentsShortHills: Number,
    totalIsolationsShortHills: Number,
    totalQuarantinesShortHills: Number,
    totalActiveIsolationsShortHills: Number,
    totalActiveQuarantinesShortHills: Number,
    percentShortHillsActiveIsolationOrQuarantine: Number,
    past72IsolationsShortHills: Number,
    past72QuarantinesShortHills: Number,
    cohort1ShortHills: Number,
    cohort1ActiveIsolationsShortHills: Number,
    cohort1ActiveQuarantinesShortHills: Number,
    cohort1NewIsolationsShortHills: Number,
    cohort1NewQuarantinesShortHills: Number,
    cohort2ShortHills: Number,
    cohort2ActiveIsolationsShortHills: Number,
    cohort2ActiveQuarantinesShortHills: Number,
    cohort2NewIsolationsShortHills: Number,
    cohort2NewQuarantinesShortHills: Number,
    shortHillsAdults: Number,
    shortHillsAdultsActiveIsolations: Number,
    shortHillsAdultsActiveQuarantines: Number,
    studentsBaskingRidge: Number,
    totalIsolationsBaskingRidge: Number,
    totalQuarantinesBaskingRidge: Number,
    totalActiveIsolationsBaskingRidge: Number,
    totalActiveQuarantinesBaskingRidge: Number,
    percentBaskingRidgeActiveIsolationOrQuarantine: Number,
    percentPingryActiveIsolationOrQuarantine: Number,
    past72IsolationsBaskingRidge: Number,
    past72QuarantinesBaskingRidge: Number,
    cohort1BaskingRidge: Number,
    cohort1ActiveIsolationsBaskingRidge: Number,
    cohort1ActiveQuarantinesBaskingRidge: Number,
    cohort1NewIsolationsBaskingRidge: Number,
    cohort1NewQuarantinesBaskingRidge: Number,
    cohort2BaskingRidge: Number,
    cohort2ActiveIsolationsBaskingRidge: Number,
    cohort2ActiveQuarantinesBaskingRidge: Number,
    cohort2NewIsolationsBaskingRidge: Number,
    cohort2NewQuarantinesBaskingRidge: Number,
    baskingRidgeAdults: Number,
    baskingRidgeAdultsActiveIsolations: Number,
    baskingRidgeAdultsActiveQuarantines: Number,
    outOfSchoolHash: Array}]
}, {timestamps: true});

const PingryInternal = mongoose.model("PingryInternal", pingryInternalSchema);
module.exports = PingryInternal;